
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1Choice ( name = "BugValueType" )
    public class BugValueType {
            
        @ASN1Element ( name = "bugPrimitive", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private BugPrimitive bugPrimitive = null;
                
  
        @ASN1Element ( name = "bugEnum", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private BugEnum bugEnum = null;
                
  
        
        public BugPrimitive getBugPrimitive () {
            return this.bugPrimitive;
        }

        public boolean isBugPrimitiveSelected () {
            return this.bugPrimitive != null;
        }

        private void setBugPrimitive (BugPrimitive value) {
            this.bugPrimitive = value;
        }

        public void selectBugPrimitive (BugPrimitive value) {
            this.bugPrimitive = value;
            
                    setBugEnum(null);
                            
        }
        
  
        
        public BugEnum getBugEnum () {
            return this.bugEnum;
        }

        public boolean isBugEnumSelected () {
            return this.bugEnum != null;
        }

        private void setBugEnum (BugEnum value) {
            this.bugEnum = value;
        }

        public void selectBugEnum (BugEnum value) {
            this.bugEnum = value;
            
                    setBugPrimitive(null);
                            
        }
        
  
    }
            