
package org.bn.mq.protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1Sequence ( name = "AliveRequest", isSet = false )
    public class AliveRequest {
            @ASN1Integer( name = "" )
    
        @ASN1Element ( name = "timestamp", isOptional =  false , hasTag =  false  , hasDefaultValue =  false  )
    
	private Long timestamp = null;
                
  
        
        public Long getTimestamp () {
            return this.timestamp;
        }

        

        public void setTimestamp (Long value) {
            this.timestamp = value;
        }
        
  
                    
        
        
        public void initWithDefaults() {
            
        }
            
    }
            