
package org.bn.mq.protocol;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1Choice ( name = "MessageBody" )
    public class MessageBody {
            @ASN1OctetString( name = "" )
    
        @ASN1Element ( name = "userBody", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private byte[] userBody = null;
                
  
        @ASN1Element ( name = "deliveryReport", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private DeliveryReport deliveryReport = null;
                
  
        @ASN1Element ( name = "subscribeRequest", isOptional =  false , hasTag =  true, tag = 2 , hasDefaultValue =  false  )
    
	private SubscribeRequest subscribeRequest = null;
                
  
        @ASN1Element ( name = "subscribeResult", isOptional =  false , hasTag =  true, tag = 3 , hasDefaultValue =  false  )
    
	private SubscribeResult subscribeResult = null;
                
  
        @ASN1Element ( name = "unsubscribeRequest", isOptional =  false , hasTag =  true, tag = 4 , hasDefaultValue =  false  )
    
	private UnsubscribeRequest unsubscribeRequest = null;
                
  
        @ASN1Element ( name = "lookupRequest", isOptional =  false , hasTag =  true, tag = 5 , hasDefaultValue =  false  )
    
	private LookupRequest lookupRequest = null;
                
  
        @ASN1Element ( name = "lookupResult", isOptional =  false , hasTag =  true, tag = 6 , hasDefaultValue =  false  )
    
	private LookupResult lookupResult = null;
                
  
        
        public byte[] getUserBody () {
            return this.userBody;
        }

        public boolean isUserBodySelected () {
            return this.userBody != null;
        }

        private void setUserBody (byte[] value) {
            this.userBody = value;
        }

        public void selectUserBody (byte[] value) {
            this.userBody = value;
            
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                            
        }
        
  
        
        public DeliveryReport getDeliveryReport () {
            return this.deliveryReport;
        }

        public boolean isDeliveryReportSelected () {
            return this.deliveryReport != null;
        }

        private void setDeliveryReport (DeliveryReport value) {
            this.deliveryReport = value;
        }

        public void selectDeliveryReport (DeliveryReport value) {
            this.deliveryReport = value;
            
                    setUserBody(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                            
        }
        
  
        
        public SubscribeRequest getSubscribeRequest () {
            return this.subscribeRequest;
        }

        public boolean isSubscribeRequestSelected () {
            return this.subscribeRequest != null;
        }

        private void setSubscribeRequest (SubscribeRequest value) {
            this.subscribeRequest = value;
        }

        public void selectSubscribeRequest (SubscribeRequest value) {
            this.subscribeRequest = value;
            
                    setUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                            
        }
        
  
        
        public SubscribeResult getSubscribeResult () {
            return this.subscribeResult;
        }

        public boolean isSubscribeResultSelected () {
            return this.subscribeResult != null;
        }

        private void setSubscribeResult (SubscribeResult value) {
            this.subscribeResult = value;
        }

        public void selectSubscribeResult (SubscribeResult value) {
            this.subscribeResult = value;
            
                    setUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setUnsubscribeRequest(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                            
        }
        
  
        
        public UnsubscribeRequest getUnsubscribeRequest () {
            return this.unsubscribeRequest;
        }

        public boolean isUnsubscribeRequestSelected () {
            return this.unsubscribeRequest != null;
        }

        private void setUnsubscribeRequest (UnsubscribeRequest value) {
            this.unsubscribeRequest = value;
        }

        public void selectUnsubscribeRequest (UnsubscribeRequest value) {
            this.unsubscribeRequest = value;
            
                    setUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setLookupRequest(null);
                
                    setLookupResult(null);
                            
        }
        
  
        
        public LookupRequest getLookupRequest () {
            return this.lookupRequest;
        }

        public boolean isLookupRequestSelected () {
            return this.lookupRequest != null;
        }

        private void setLookupRequest (LookupRequest value) {
            this.lookupRequest = value;
        }

        public void selectLookupRequest (LookupRequest value) {
            this.lookupRequest = value;
            
                    setUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setLookupResult(null);
                            
        }
        
  
        
        public LookupResult getLookupResult () {
            return this.lookupResult;
        }

        public boolean isLookupResultSelected () {
            return this.lookupResult != null;
        }

        private void setLookupResult (LookupResult value) {
            this.lookupResult = value;
        }

        public void selectLookupResult (LookupResult value) {
            this.lookupResult = value;
            
                    setUserBody(null);
                
                    setDeliveryReport(null);
                
                    setSubscribeRequest(null);
                
                    setSubscribeResult(null);
                
                    setUnsubscribeRequest(null);
                
                    setLookupRequest(null);
                            
        }
        
  
    }
            