
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "BugEnum" )]
    public class BugEnum {
    
            private int val;
            
            [ASN1Integer( Name = "BugEnum" )]
            
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public BugEnum() {
            }

            public BugEnum(int value) {
                this.Value = value;
            }            
    }
            
}
