
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;



    @ASN1Sequence ( name = "DataSeq" )
    public class DataSeq {
            
        @ASN1Element ( name = "plain", isOptional =  false , hasTag =  true, tag = 0 )
    
	private TestPRN plain = null;
                
  
        @ASN1Element ( name = "unicode", isOptional =  true , hasTag =  true, tag = 1 )
    
	private TestOCT unicode = null;
                
  
        @ASN1Element ( name = "binary", isOptional =  false , hasTag =  true, tag = 2 )
    
	private TestOCT binary = null;
                
  
        @ASN1Element ( name = "simpleType", isOptional =  false , hasTag =  true, tag = 3 )
    @ASN1String( name = "", 
        stringType =  UniversalTag.PrintableString , isUCS = false )
	private String simpleType = null;
                
  
        @ASN1Element ( name = "simpleOctType", isOptional =  false , hasTag =  false  )
    @ASN1OctetString( name = "" )
    
	private byte[] simpleOctType = null;
                
  
        @ASN1Element ( name = "booleanType", isOptional =  false , hasTag =  true, tag = 5 )
    @ASN1Boolean( name = "" )
    
	private Boolean booleanType = null;
                
  
        @ASN1Element ( name = "intType", isOptional =  false , hasTag =  true, tag = 6 )
    @ASN1Integer( name = "" )
    
	private Integer intType = null;
                
  
        @ASN1Element ( name = "intBndType", isOptional =  false , hasTag =  true, tag = 7 )
    @ASN1Integer( name = "" )
    @ASN1ValueRangeConstraint ( 
		min = 0L, 
		max = 255L ) 
	   
	private Integer intBndType = null;
                
  
        @ASN1Element ( name = "stringArray", isOptional =  false , hasTag =  true, tag = 8 )
    @ASN1SequenceOf( name = "" ) 
@ASN1String( name = "", 
        stringType =  UniversalTag.PrintableString , isUCS = false )
	private java.util.Collection<String>  stringArray = null;
                
  
        @ASN1Element ( name = "dataArray", isOptional =  false , hasTag =  true, tag = 9 )
    @ASN1SequenceOf( name = "" ) 

	private java.util.Collection<Data>  dataArray = null;
                
  
        @ASN1Element ( name = "extension", isOptional =  true , hasTag =  false  )
    @ASN1Any( name = "" )
    
	private byte[] extension = null;
                
  
        
        public TestPRN getPlain () {
            return this.plain;
        }

        

        public void setPlain (TestPRN value) {
            this.plain = value;
        }
        
  
        
        public TestOCT getUnicode () {
            return this.unicode;
        }

        
        public boolean isUnicodePresent () {
            return this.unicode == null;
        }
        

        public void setUnicode (TestOCT value) {
            this.unicode = value;
        }
        
  
        
        public TestOCT getBinary () {
            return this.binary;
        }

        

        public void setBinary (TestOCT value) {
            this.binary = value;
        }
        
  
        
        public String getSimpleType () {
            return this.simpleType;
        }

        

        public void setSimpleType (String value) {
            this.simpleType = value;
        }
        
  
        
        public byte[] getSimpleOctType () {
            return this.simpleOctType;
        }

        

        public void setSimpleOctType (byte[] value) {
            this.simpleOctType = value;
        }
        
  
        
        public Boolean getBooleanType () {
            return this.booleanType;
        }

        

        public void setBooleanType (Boolean value) {
            this.booleanType = value;
        }
        
  
        
        public Integer getIntType () {
            return this.intType;
        }

        

        public void setIntType (Integer value) {
            this.intType = value;
        }
        
  
        
        public Integer getIntBndType () {
            return this.intBndType;
        }

        

        public void setIntBndType (Integer value) {
            this.intBndType = value;
        }
        
  
        
        public java.util.Collection<String>  getStringArray () {
            return this.stringArray;
        }

        

        public void setStringArray (java.util.Collection<String>  value) {
            this.stringArray = value;
        }
        
  
        
        public java.util.Collection<Data>  getDataArray () {
            return this.dataArray;
        }

        

        public void setDataArray (java.util.Collection<Data>  value) {
            this.dataArray = value;
        }
        
  
        
        public byte[] getExtension () {
            return this.extension;
        }

        
        public boolean isExtensionPresent () {
            return this.extension == null;
        }
        

        public void setExtension (byte[] value) {
            this.extension = value;
        }
        
  
    }
            