
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;



    @ASN1BoxedType ( name = "DataSeqArray" )
    public class DataSeqArray {
    
            @ASN1SequenceOf( name = "DataSeqArray" )
            
	    private java.util.Collection<DataSeq> value = null; 
                        
            public void setValue(java.util.Collection<DataSeq> value) {
                this.value = value;
            }
            
            public java.util.Collection<DataSeq> getValue() {
                return this.value;
            }
    }
            