
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;



    @ASN1BoxedType ( name = "ITUType6" )
    public class ITUType6 {
            
            
        @ASN1Element ( name = "ITUType6", isOptional =  false , hasTag =  true, tag = 9 )
    @ASN1String( name = "", 
        stringType =  UniversalTag.VisibleString , isUCS = false ) private String  value;

        
        
        public void setValue(String value) {
            this.value = value;
        }
        
        public String getValue() {
            return this.value;
        }            
        
            
    }
            