
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;



    @ASN1Sequence ( name = "SequenceWithNull" )
    public class SequenceWithNull {
            
        @ASN1Element ( name = "test", isOptional =  false , hasTag =  false  )
    @ASN1String( name = "", 
        stringType =  UniversalTag.PrintableString , isUCS = false )
	private String test = null;
                
  
        @ASN1Element ( name = "nullVal", isOptional =  false , hasTag =  false  )
    
        @ASN1Null ( name = "nullVal" ) 
    
	private Object nullVal = null;
                
  
        @ASN1Element ( name = "test2", isOptional =  false , hasTag =  true, tag = 1 )
    @ASN1String( name = "", 
        stringType =  UniversalTag.PrintableString , isUCS = false )
	private String test2 = null;
                
  
        
        public String getTest () {
            return this.test;
        }

        

        public void setTest (String value) {
            this.test = value;
        }
        
  
        
        public String getTest2 () {
            return this.test2;
        }

        

        public void setTest2 (String value) {
            this.test2 = value;
        }
        
  
    }
            