
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;



    @ASN1BoxedType ( name = "TaggedSequence" )
    public class TaggedSequence {
            
            
       @ASN1Sequence ( name = "TaggedSequence" )
       public class SequenceType {
                
        @ASN1Element ( name = "type1", isOptional =  true , hasTag =  true, tag = 7 )
    @ASN1String( name = "", 
        stringType =  UniversalTag.VisibleString , isUCS = false )
	private String type1 = null;
                
  
       }
                
        @ASN1Element ( name = "TaggedSequence", isOptional =  false , hasTag =  true, tag = 8, 
        tagClass =  TagClass.Application  )
     private SequenceType  value;

        
        
        public void setValue(SequenceType value) {
            this.value = value;
        }
        
        public SequenceType getValue() {
            return this.value;
        }            
        
            
    }
            