
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;



    @ASN1BoxedType ( name = "ITUType4" )
    public class ITUType4 {
            
            
        @ASN1Element ( name = "ITUType4", isOptional =  false , hasTag =  true, tag = 7, 
        tagClass =  TagClass.Application  )
     private ITUType3  value;

        
        
        public void setValue(ITUType3 value) {
            this.value = value;
        }
        
        public ITUType3 getValue() {
            return this.value;
        }            
        
            
    }
            