
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;



    @ASN1BoxedType ( name = "ITUType3" )
    public class ITUType3 {
            
            
        @ASN1Element ( name = "ITUType3", isOptional =  false , hasTag =  true, tag = 2 )
     private ITUType2  value;

        
        
        public void setValue(ITUType2 value) {
            this.value = value;
        }
        
        public ITUType2 getValue() {
            return this.value;
        }            
        
            
    }
            