
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;



    @ASN1BoxedType ( name = "TestOCT" )
    public class TestOCT {
    
            @ASN1OctetString( name = "TestOCT" )
            private byte[] value = null;
            
            public TestOCT() {
            }

            public TestOCT(byte[] value) {
                this.value = value;
            }
            
            public void setValue(byte[] value) {
                this.value = value;
            }
            
            public byte[] getValue() {
                return this.value;
            }
    }
            