
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;

namespace org.bn.mq.protocol {


    [ASN1PreparedElement]
    [ASN1Sequence ( Name = "DeliveryReport", IsSet = false  )]
    public class DeliveryReport : IASN1PreparedElement {
            
        
	private string messageId_ ;
	[ASN1String( Name = "", 
        StringType =  UniversalTags.PrintableString , IsUCS = false )][ASN1ValueRangeConstraint ( 
		Min = 0L, 
		Max = 10L ) ]
	    
        [ASN1Element ( Name = "messageId", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public string MessageId
        {
            get { return messageId_; }
            set { messageId_ = value;  }
        }
        
                
  
        
	private DeliveredStatus status_ ;
	
        [ASN1Element ( Name = "status", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public DeliveredStatus Status
        {
            get { return status_; }
            set { status_ = value;  }
        }
        
                
  
        
	private int deliveredCount_ ;
	[ASN1Integer( Name = "" )]
    [ASN1ValueRangeConstraint ( 
		Min = 0L, 
		Max = 65535L ) ]
	    
        [ASN1Element ( Name = "deliveredCount", IsOptional =  false , HasTag =  false  , HasDefaultValue =  false )  ]
    
        public int DeliveredCount
        {
            get { return deliveredCount_; }
            set { deliveredCount_ = value;  }
        }
        
                
  

            public void initWithDefaults() {
                
            }


            private static IASN1PreparedElementData preparedData = new ASN1PreparedElementData(typeof(DeliveryReport));
            public IASN1PreparedElementData PreparedData {
            	get { return preparedData; }
            }

            
    }
            
}
