
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1BoxedType ( name = "ContentPartHeaders" )
    public class ContentPartHeaders {
                
            @ASN1SequenceOf( name = "ContentPartHeaders" , isSetOf = false)
            
	    private java.util.Collection<ContentPartHeader> value = null; 
    
            public ContentPartHeaders () {
            }
        
            public ContentPartHeaders ( java.util.Collection<ContentPartHeader> value ) {
                setValue(value);
            }
                        
            public void setValue(java.util.Collection<ContentPartHeader> value) {
                this.value = value;
            }
            
            public java.util.Collection<ContentPartHeader> getValue() {
                return this.value;
            }            
            
            public void initValue() {
                setValue(new java.util.LinkedList<ContentPartHeader>()); 
            }
            
            public void add(ContentPartHeader item) {
                value.add(item);
            }
    }
            