
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1BoxedType ( name = "TaggedSequence" )
    public class TaggedSequence {
                
        
       @ASN1Sequence ( name = "TaggedSequence" , isSet = false )
       public class TaggedSequenceSequenceType {
                
    @ASN1String( name = "", 
        stringType =  UniversalTag.VisibleString , isUCS = false )
    
        @ASN1Element ( name = "type1", isOptional =  true , hasTag =  true, tag = 7 , hasDefaultValue =  false  )
    
	private String type1 = null;
                
  
        
        public String getType1 () {
            return this.type1;
        }

        
        public boolean isType1Present () {
            return this.type1 == null;
        }
        

        public void setType1 (String value) {
            this.type1 = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }
                
       }
       
                
        @ASN1Element ( name = "TaggedSequence", isOptional =  false , hasTag =  true, tag = 8, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private TaggedSequenceSequenceType  value;        

        
        
        public TaggedSequence () {
        }
        
        
        
        public void setValue(TaggedSequenceSequenceType value) {
            this.value = value;
        }
        
        
        
        public TaggedSequenceSequenceType getValue() {
            return this.value;
        }            
        
            
    }
            