
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1BoxedType ( name = "TestBitStrBnd" )
    public class TestBitStrBnd {
    
            @ASN1BitString( name = "TestBitStrBnd" )
            @ASN1ValueRangeConstraint ( 
		min = 1L, 
		max = 16L ) 
	   
            private BitString value = null;
            
            public TestBitStrBnd() {
            }

            public TestBitStrBnd(BitString value) {
                this.value = value;
            }
            
            public void setValue(BitString value) {
                this.value = value;
            }
            
            public BitString getValue() {
                return this.value;
            }
    }
            