
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1BoxedType ( name = "TaggedSeqInSeq" )
    public class TaggedSeqInSeq {
                
        
       @ASN1Sequence ( name = "TaggedSeqInSeq" , isSet = false )
       public class TaggedSeqInSeqSequenceType {
                
        @ASN1Element ( name = "field", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private PlainParamsMap field = null;
                
  
        
        public PlainParamsMap getField () {
            return this.field;
        }

        

        public void setField (PlainParamsMap value) {
            this.field = value;
        }
        
  
                
                
        public void initWithDefaults() {
            
        }
                
       }
       
                
        @ASN1Element ( name = "TaggedSeqInSeq", isOptional =  false , hasTag =  true, tag = 4, 
        tagClass =  TagClass.Application  , hasDefaultValue =  false  )
    
        private TaggedSeqInSeqSequenceType  value;        

        
        
        public TaggedSeqInSeq () {
        }
        
        
        
        public void setValue(TaggedSeqInSeqSequenceType value) {
            this.value = value;
        }
        
        
        
        public TaggedSeqInSeqSequenceType getValue() {
            return this.value;
        }            
        
            
    }
            