
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.CoderFactory;
import org.bn.annotations.ASN1Element;
import org.bn.annotations.ASN1ObjectIdentifier;
import org.bn.annotations.ASN1PreparedElement;
import org.bn.annotations.ASN1Sequence;
import org.bn.coders.IASN1PreparedElement;
import org.bn.coders.IASN1PreparedElementData;
import org.bn.types.ObjectIdentifier;




    @ASN1PreparedElement
    @ASN1Sequence ( name = "TestSeqWithOID", isSet = false )
    public class TestSeqWithOID implements IASN1PreparedElement {
            @ASN1ObjectIdentifier( name = "" )
    
        @ASN1Element ( name = "protcolId", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private ObjectIdentifier protcolId = null;
                
  
        
        public ObjectIdentifier getProtcolId () {
            return this.protcolId;
        }

        

        public void setProtcolId (ObjectIdentifier value) {
            this.protcolId = value;
        }
        
  
                    
        
        public void initWithDefaults() {
            
        }

        private static IASN1PreparedElementData preparedData = CoderFactory.getInstance().newPreparedElementData(TestSeqWithOID.class);
        public IASN1PreparedElementData getPreparedData() {
            return preparedData;
        }

            
    }
            