
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "TaggedSeqInSeq") ]
    public class TaggedSeqInSeq {
            
           
        private TaggedSeqInSeqSequenceType  val;

        
       [ASN1Sequence ( Name = "TaggedSeqInSeq", IsSet = false  )]
       public class TaggedSeqInSeqSequenceType {
                
        
	private PlainParamsMap field_ ;
	
        [ASN1Element ( Name = "field", IsOptional =  false , HasTag =  true, Tag = 0 , HasDefaultValue =  false )  ]
    
        public PlainParamsMap Field
        {
            get { return field_; }
            set { field_ = value;  }
        }
        
                
  
                
                public void initWithDefaults() {
                    
                }
                
       }
                
        [ASN1Element ( Name = "TaggedSeqInSeq", IsOptional =  false , HasTag =  true, Tag = 4, 
        TagClass =  TagClasses.Application  , HasDefaultValue =  false )  ]
    
        public TaggedSeqInSeqSequenceType Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            

                    
        
        public TaggedSeqInSeq ()
        {
        }
        
    }
            
}
