
//
// This file was generated by the BinaryNotes compiler.
// See http://bn.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;

namespace test.org.bn.coders.test_asn {


    [ASN1Sequence ( Name = "ContentPartHeader" )]
    public class ContentPartHeader {
            
        
	private string name_ ;
	
        [ASN1Element ( Name = "name", IsOptional =  false , HasTag =  true, Tag = 0) ]
    [ASN1String( Name = "", 
        StringType =  UniversalTags.PrintableString , IsUCS = false )]
        public string Name
        {
            get { return name_; }
            set { name_ = value;  }
        }
        
                
  
        
	private System.Collections.Generic.ICollection<ValueWithParams>  values_ ;
	
        [ASN1Element ( Name = "values", IsOptional =  false , HasTag =  true, Tag = 1) ]
    [ASN1SequenceOf( Name = "" )]

        public System.Collections.Generic.ICollection<ValueWithParams>  Values
        {
            get { return values_; }
            set { values_ = value;  }
        }
        
                
  
    }
            
}
