
//
// This file was generated by the BinaryNotes compiler.
// See http://bn.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "ITUType6") ]
    public class ITUType6 {
            
            
            
        private string  val;

        
        [ASN1Element ( Name = "ITUType6", IsOptional =  false , HasTag =  true, Tag = 9) ]
    [ASN1String( Name = "", 
        StringType =  UniversalTags.VisibleString , IsUCS = false )] 
        public string Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            
    }
            
}
