
//
// This file was generated by the BinaryNotes compiler.
// See http://bn.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "TestI" )]
    public class TestI {
    
            private int val;
            
            [ASN1Integer( Name = "TestI" )]
            
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public TestI() {
            }

            public TestI(int value) {
                this.Value = value;
            }            
    }
            
}
