
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "TestNI2" )]
    public class TestNI2 {
    
            private int val;
            
            [ASN1Integer( Name = "TestNI2" )]
            [ASN1ValueRangeConstraint ( 
		Min = -2048L, 
		Max = 2048L ) ]
	    
            public int Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public TestNI2() {
            }

            public TestNI2(int value) {
                this.Value = value;
            }            
    }
            
}
