
package test.org.bn.coders.test_asn;
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

import org.bn.*;
import org.bn.annotations.*;
import org.bn.annotations.constraints.*;
import org.bn.coders.*;
import org.bn.types.*;




    @ASN1Choice ( name = "BugPrimitive" )
    public class BugPrimitive {
            @ASN1Boolean( name = "" )
    
        @ASN1Element ( name = "bugBoolean", isOptional =  false , hasTag =  true, tag = 0 , hasDefaultValue =  false  )
    
	private Boolean bugBoolean = null;
                
  @ASN1Integer( name = "" )
    
        @ASN1Element ( name = "bugInteger", isOptional =  false , hasTag =  true, tag = 1 , hasDefaultValue =  false  )
    
	private Integer bugInteger = null;
                
  
        
        public Boolean getBugBoolean () {
            return this.bugBoolean;
        }

        public boolean isBugBooleanSelected () {
            return this.bugBoolean != null;
        }

        private void setBugBoolean (Boolean value) {
            this.bugBoolean = value;
        }

        public void selectBugBoolean (Boolean value) {
            this.bugBoolean = value;
            
                    setBugInteger(null);
                            
        }
        
  
        
        public Integer getBugInteger () {
            return this.bugInteger;
        }

        public boolean isBugIntegerSelected () {
            return this.bugInteger != null;
        }

        private void setBugInteger (Integer value) {
            this.bugInteger = value;
        }

        public void selectBugInteger (Integer value) {
            this.bugInteger = value;
            
                    setBugBoolean(null);
                            
        }
        
  
    }
            