
//
// This file was generated by the BinaryNotes compiler.
// See http://bn.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "ITUType4") ]
    public class ITUType4 {
            
            
            
        private ITUType3  val;

        
        [ASN1Element ( Name = "ITUType4", IsOptional =  false , HasTag =  true, Tag = 7, 
        TagClass =  TagClasses.Application ) ]
     
        public ITUType3 Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            
    }
            
}
