
//
// This file was generated by the BinaryNotes compiler.
// See http://bn.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;

namespace test.org.bn.coders.test_asn {


    [ASN1Sequence ( Name = "SequenceWithNull" )]
    public class SequenceWithNull {
            
        
	private string test_ ;
	
        [ASN1Element ( Name = "test", IsOptional =  false , HasTag =  false ) ]
    [ASN1String( Name = "", 
        StringType =  UniversalTags.PrintableString , IsUCS = false )]
        public string Test
        {
            get { return test_; }
            set { test_ = value;  }
        }
        
                
  
        
	private object nullVal_ ;
	
        [ASN1Element ( Name = "nullVal", IsOptional =  false , HasTag =  false ) ]
    
        [ASN1Null ( Name = "nullVal" )]
    
        public object NullVal
        {
            get { return nullVal_; }
            set { nullVal_ = value;  }
        }
        
                
  
        
	private string test2_ ;
	
        [ASN1Element ( Name = "test2", IsOptional =  false , HasTag =  true, Tag = 1) ]
    [ASN1String( Name = "", 
        StringType =  UniversalTags.PrintableString , IsUCS = false )]
        public string Test2
        {
            get { return test2_; }
            set { test2_ = value;  }
        }
        
                
  
    }
            
}
