
//
// This file was generated by the BinaryNotes compiler.
// See http://bn.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "StringArray") ]
    public class StringArray {

	    private System.Collections.Generic.ICollection<string> val = null; 
            
            [ASN1SequenceOf( Name = "StringArray") ]
            [ASN1String( Name = "", 
        StringType =  UniversalTags.PrintableString , IsUCS = false )]
            public System.Collections.Generic.ICollection<string> Value
            {
                get { return val; }
                set { val = value; }
            }
    }
            
}
