
//
// This file was generated by the BinaryNotes compiler.
// See http://bn.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "TaggedSequence") ]
    public class TaggedSequence {
            
            
       [ASN1Sequence ( Name = "TaggedSequence") ]
       public class SequenceType {
                
        
	private string type1_ ;
	
        private bool  type1_present = false ;
	
        [ASN1Element ( Name = "type1", IsOptional =  true , HasTag =  true, Tag = 7) ]
    [ASN1String( Name = "", 
        StringType =  UniversalTags.VisibleString , IsUCS = false )]
        public string Type1
        {
            get { return type1_; }
            set { type1_ = value; type1_present = true;  }
        }
        
                
  
       }
                
            
        private SequenceType  val;

        
        [ASN1Element ( Name = "TaggedSequence", IsOptional =  false , HasTag =  true, Tag = 8, 
        TagClass =  TagClasses.Application ) ]
     
        public SequenceType Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            
    }
            
}
