
//
// This file was generated by the BinaryNotes compiler.
// See http://bn.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;

namespace test.org.bn.coders.test_asn {


    [ASN1Sequence ( Name = "TestRecursiveDefinetion" )]
    public class TestRecursiveDefinetion {
            
        
	private string name_ ;
	
        [ASN1Element ( Name = "name", IsOptional =  false , HasTag =  true, Tag = 1) ]
    [ASN1String( Name = "", 
        StringType =  UniversalTags.PrintableString , IsUCS = false )]
        public string Name
        {
            get { return name_; }
            set { name_ = value;  }
        }
        
                
  
        
	private TestRecursiveDefinetion value_ ;
	
        private bool  value_present = false ;
	
        [ASN1Element ( Name = "value", IsOptional =  true , HasTag =  true, Tag = 2) ]
    
        public TestRecursiveDefinetion Value
        {
            get { return value_; }
            set { value_ = value; value_present = true;  }
        }
        
                
  
        public bool isValuePresent () {
            return this.value_present == true;
        }
        
    }
            
}
