
//
// This file was generated by the BinaryNotes compiler.
// See http://bn.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;

namespace test.org.bn.coders.test_asn {


    [ASN1Sequence ( Name = "ValueWithParams" )]
    public class ValueWithParams {
            
        
	private string value_ ;
	
        [ASN1Element ( Name = "value", IsOptional =  false , HasTag =  true, Tag = 0) ]
    [ASN1String( Name = "", 
        StringType =  UniversalTags.PrintableString , IsUCS = false )]
        public string Value
        {
            get { return value_; }
            set { value_ = value;  }
        }
        
                
  
        
	private System.Collections.Generic.ICollection<PlainParamsMap>  params_ ;
	
        private bool  params_present = false ;
	
        [ASN1Element ( Name = "params", IsOptional =  true , HasTag =  true, Tag = 1) ]
    [ASN1SequenceOf( Name = "" )]

        public System.Collections.Generic.ICollection<PlainParamsMap>  Params
        {
            get { return params_; }
            set { params_ = value; params_present = true;  }
        }
        
                
  
        public bool isParamsPresent () {
            return this.params_present == true;
        }
        
    }
            
}
