
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "BugList" ) ]
    public class BugList {

	    private System.Collections.Generic.ICollection<BugValueType> val = null; 
            
            [ASN1SequenceOf( Name = "BugList", IsSetOf = false) ]
            
            public System.Collections.Generic.ICollection<BugValueType> Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public void initValue() {
                this.Value = new System.Collections.Generic.List<BugValueType>();
            }
            
            public void Add(BugValueType item) {
                this.Value.Add(item);
            }
    }
            
}
