
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "TestLong" )]
    public class TestLong {
    
            private long val;
            
            [ASN1Integer( Name = "TestLong" )]
            [ASN1ValueRangeConstraint ( 
		Min = 1L, 
		Max = 2247483648L ) ]
	    
            public long Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public TestLong() {
            }

            public TestLong(long value) {
                this.Value = value;
            }            
    }
            
}
