
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "ITUType2") ]
    public class ITUType2 {
            
           
        private ITUType1  val;

        
        [ASN1Element ( Name = "ITUType2", IsOptional =  false , HasTag =  true, Tag = 3, 
        TagClass =  TagClasses.Application  , HasDefaultValue =  false )  ]
    
        public ITUType1 Value
        {
                get { return val; }        
                    
                set { val = value; }
                        
        }            

                    
        
        public ITUType2 ()
        {
        }
        
    }
            
}
