
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "StringArray" ) ]
    public class StringArray {

	    private System.Collections.Generic.ICollection<string> val = null; 
            
            [ASN1SequenceOf( Name = "StringArray", IsSetOf = false) ]
            [ASN1String( Name = "", 
        StringType =  UniversalTags.PrintableString , IsUCS = false )]
            public System.Collections.Generic.ICollection<string> Value
            {
                get { return val; }
                set { val = value; }
            }
            
            public void initValue() {
                this.Value = new System.Collections.Generic.List<string>();
            }
            
            public void Add(string item) {
                this.Value.Add(item);
            }
    }
            
}
