
//
// This file was generated by the BinaryNotes compiler.
// See http://bnotes.sourceforge.net 
// Any modifications to this file will be lost upon recompilation of the source ASN.1. 
//

using System;
using org.bn.attributes;
using org.bn.attributes.constraints;
using org.bn.coders;
using org.bn.types;

namespace test.org.bn.coders.test_asn {


    [ASN1BoxedType ( Name = "TestBitStrBnd") ]
    public class TestBitStrBnd {
    
            private BitString val = null;

            [ASN1BitString( Name = "TestBitStrBnd") ]            
            [ASN1ValueRangeConstraint ( 
		Min = 1L, 
		Max = 16L ) ]
	    
            public BitString Value
            {
                get { return val; }
                set { val = value; }
            }            
            
            public TestBitStrBnd() {
            }

            public TestBitStrBnd(BitString value) {
                this.Value = value;
            }            
    }
            
}
